mycrm/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView

from . import views

app_name = 'mycrm'
urlpatterns = [

    #record
    path('record', views.select_type, name='select-record-type'),
    
    path('record/group/<int:group_id>', views.post_record, name='add-record'),
    path('record/<int:record_id>', views.detail, name='detail'),
    path('summary', views.summary, name='summary'),
    
    #record group
    path('recordgroup', views.post_record_group, name='add-record-group'),
    path('company', views.post_company, name='add-company'),

    path('login', views.sign_in, name='sign-in'),
    path('signup', views.sign_up, name='sign-up'),
    
    path('home', views.home, name='home'),
    path('dash', views.dash, name='dash'),


    path('dataloader', views.data_loader, name='data=loader'),
    
    path("logout", LogoutView.as_view(), name="logout"),
    path('buttons', views.buttons, name='buttons'),
    path('settings', views.settings, name='settings'),
    path('forms', views.forms, name='forms'),
    path('modals', views.modals, name='modals'),
    path('bootstrap-tables', views.bootstrap_tables, name='bootstrap_tables'),
]

simple_crm/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('mycrm/', include('mycrm.urls')),
    path('admin/', admin.site.urls),
    path("", include("frontpage.urls")),
]

mycrm/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.contrib import admin
from django.db.models import JSONField

class Base(models.Model):
    created_by = models.CharField(max_length=200, default="admin")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_by = models.CharField(max_length=200, default="admin")
    updated_at = models.DateTimeField(auto_now=True)
    class Meta:
        abstract = True

class Company(Base):
    company_name = models.CharField(max_length=50)
    def __str__(self):
        return self.id

class RecordGroup(Base):
    group_name = models.CharField(max_length=50)
    company = models.ForeignKey(Company, on_delete=models.CASCADE)

    numberOfFields = models.IntegerField(default=0)
    field_definitions = JSONField(default=dict)
    def __str__(self):
        return self.id

class Record(Base):
    custom_fields = JSONField(default=dict)
    record_group = models.ForeignKey(RecordGroup, on_delete=models.CASCADE)
    def __str__(self):
        return self.id

mycrm/forms/company.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class AddCompanyForm(forms.Form):
    company_name = forms.CharField(label='Company Name', max_length=100)

mycrm/forms/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class AddRecordForm(forms.Form):
    record_type = forms.CharField(label='Record Type', max_length=100)

    def __init__(self, *args, **kwargs):
        custom_fields = kwargs.pop('custom_fields', -1)
        print(custom_fields)

        super(AddRecordForm, self).__init__(*args, **kwargs)
        for index in range(int(custom_fields)):
            self.fields['custom_field_{index}'.format(index=index)] = \
                forms.CharField()


class UpdateRecordForm(forms.Form):
    first_name = forms.CharField(label='First Name', max_length=100)
    last_name = forms.CharField(label='Last Name', max_length=100)
    record_type = forms.CharField(label='Record Type', max_length=100)

class SelectRecordTypeForm(forms.Form):
    record_type = forms.CharField(label='Record Type', max_length=100)

class LoginForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder" : "Username",                
                "class": "form-control"
            }
        ))
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder" : "Password",                
                "class": "form-control"
            }
        ))

class SignUpForm(UserCreationForm):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder" : "Username",                
                "class": "form-control"
            }
        ))
    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={
                "placeholder" : "Email",                
                "class": "form-control"
            }
        ))
    password1 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder" : "Password",                
                "class": "form-control"
            }
        ))
    password2 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder" : "Password check",                
                "class": "form-control"
            }
        ))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

mycrm/forms/record_group.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class AddRecordGroupForm(forms.Form):
    group_name = forms.CharField(label='Group Name', max_length=100)
    company = forms.CharField(label='Company', max_length=100)
    custom_field_count = forms.CharField(widget=forms.HiddenInput())

    def __init__(self, *args, **kwargs):
        custom_fields = kwargs.pop('custom_fields', -1)
        print(custom_fields)

        super(AddRecordGroupForm, self).__init__(*args, **kwargs)
        self.fields['custom_field_count'].initial = custom_fields

        for index in range(int(custom_fields)):
            self.fields['custom_field_{index}'.format(index=index)] = \
                forms.CharField()

mycrm/views/company.py
from functools import wraps
import logging

from django.http import HttpResponseRedirect

from django.contrib.auth.decorators import login_required

from django.shortcuts import redirect, render
from django.views import generic

from mycrm.models import Company
from mycrm.forms.company import AddCompanyForm

logger = logging.getLogger(__name__)

@login_required(login_url="/mycrm/login")
def post_company(request):
    if request.method == 'POST':
        form = AddCompanyForm(request.POST)
        if form.is_valid():
            company = Company(company_name=form.cleaned_data['company_name'])
            company.save()
            
            return render(request, 'mycrm/company/add.html', { 'status': 'Successly added record.' })
        return render(request, 'mycrm/company/add.html', { 'status': form })
    else:
        return render(request, 'mycrm/company/add.html')

mycrm/views/dataloader.py
from functools import wraps
import logging

from django.http import HttpResponseRedirect

from django.contrib.auth.decorators import login_required

from django.shortcuts import redirect, render
from django.views import generic

logger = logging.getLogger(__name__)

@login_required(login_url="/mycrm/login")
def data_loader(request):
    return render(request, 'mycrm/dataloader/load.html')

mycrm/views/primary.py
from functools import wraps
import logging

from django.http import HttpResponseRedirect

from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login

from django.shortcuts import redirect, render
from django.views import generic

from mycrm.forms.forms import LoginForm
from mycrm.models import Record

logger = logging.getLogger(__name__)

class DashboardView(generic.TemplateView):
    abc = 'test'
    template_name = 'mycrm/dashboard.html'

def sign_in(request):
    form = LoginForm(request.POST or None)
    msg = None
    if request.method == "POST":
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(username=username, password=password)
            
            if user is not None:
                login(request, user)
            return redirect(request.POST.get('next', ''))
        else:
            msg = 'Error validating the form'    
    else:
        return render(request, "mycrm/accounts/sign-in.html", {"form": form, "msg" : msg})

def sign_up(request):
    return render(request, 'mycrm/sign-up.html')



@login_required(login_url="/mycrm/login")
def dash(request):
    return render(request, 'mycrm/volt/dashboard.html')

@login_required(login_url="/mycrm/login")
def home(request):
    return render(request, 'mycrm/index.html')

@login_required(login_url="/mycrm/login")
def buttons(request):
    return render(request, 'mycrm/volt/ui-buttons.html')

@login_required(login_url="/mycrm/login")
def forms(request):
    return render(request, 'mycrm/volt/ui-forms.html')
    
@login_required(login_url="/mycrm/login")
def modals(request):
    return render(request, 'mycrm/volt/ui-modals.html')

@login_required(login_url="/mycrm/login")
def settings(request):
    return render(request, 'mycrm/volt/settings.html')
    
@login_required(login_url="/mycrm/login")
def bootstrap_tables(request):
    return render(request, 'mycrm/bootstrap-tables.html')

mycrm/views/record.py
import logging
import json

from django.core import serializers
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.utils import timezone
from django.views import generic

from mycrm.forms.forms import AddRecordForm, SelectRecordTypeForm, UpdateRecordForm
from mycrm.models import Record, RecordGroup

logger = logging.getLogger(__name__)

@login_required(login_url="/mycrm/login")
def select_type(request):
    data = { 'types': RecordGroup.objects.all(), }

    if request.method == 'POST':
        form = SelectRecordTypeForm(request.POST)
        if form.is_valid():
            return redirect('record/group/' + form.cleaned_data['record_type'])
    return render(request, 'mycrm/record/select_type.html', data)

@login_required(login_url="/mycrm/login")
def post_record(request, group_id):
    
    field_definitions = RecordGroup.objects.get(pk=group_id).field_definitions
    data = { 'types': RecordGroup.objects.all(), 'field_definitions': field_definitions }
    if request.method == 'POST':
        print(len(field_definitions))
        form = AddRecordForm(request.POST, custom_fields=len(field_definitions))
        print(form)
        if form.is_valid():
            fields = {}
            for i in range(0, len(field_definitions)):
                field_name = 'custom_field_' + str(i)
                fields[field_name] = (form.cleaned_data[field_name])

            record = Record(record_group_id=form.cleaned_data['record_type'], custom_fields=fields)
            record.save()    
            data['status'] = 'Successly added record.'
        else:
            data['status'] = 'Unable to add record'
    return render(request, 'mycrm/record/add.html', data)

@login_required(login_url="/mycrm/login")
def summary(request):
    records = Record.objects.all()
    return render(request, 'mycrm/record/summary.html', { 'records': records })

@login_required(login_url="/mycrm/login")
def detail(request, record_id):
    if request.method == 'POST':
        
        form = UpdateRecordForm(request.POST)
        record = Record.objects.get(id=record_id)
        if form.is_valid():
            record.first_name = form.cleaned_data['first_name']
            record.last_name = form.cleaned_data['last_name']
            record.save()
            return render(request, 'mycrm/record/detail.html', { 'record': record })
        return render(request, 'mycrm/record/detail.html', { 'record': record })

    record = get_object_or_404(Record, pk=record_id)

    return render(request, 'mycrm/record/detail.html', { 'record': record })

mycrm/views/record_group.py
from functools import wraps
import logging
import json
from django.contrib.auth.models import Group

from django.http import HttpResponseRedirect

from django.contrib.auth.decorators import login_required

from django.shortcuts import redirect, render
from django.views import generic

from mycrm.forms.record_group import AddRecordGroupForm
from mycrm.models import Company, RecordGroup

logger = logging.getLogger(__name__)


@login_required(login_url="/mycrm/login")
def post_record_group(request):
    
    data = { 'companies': Company.objects.all(), }
    if request.method == 'POST':
        custom_field_count = request.POST.get('custom_field_count')
        form = AddRecordGroupForm(request.POST, custom_fields=custom_field_count)
        if form.is_valid():

            fields = []
            for i in range(0, int(custom_field_count)):
                field_name = 'custom_field_' + str(i)
                fields.append(form.cleaned_data[field_name])
            fieldDefs = __format_field_defs__(fields)

            record_group = RecordGroup(
                group_name=form.cleaned_data['group_name'],
                company_id=form.cleaned_data['company'],
                field_definitions=fieldDefs,
            )
            record_group.save()
            data['status'] = 'Successly added record.'
        else:
            data['status'] = 'Unable to add record'
    return render(request,'mycrm/record_type/add.html', data)


def __format_field_defs__(fields):
    fieldDefs=  {}
    
    for index, field in enumerate(fields):
        fieldDefs[str(index)] = field

    print(fieldDefs)
    return fieldDefs

mycrm/templates/mycrm/includes/navigation.html
    <nav class="navbar navbar-top navbar-expand navbar-dashboard navbar-dark ps-0 pe-2 pb-0">
        <div class="container-fluid px-0">
          <div class="d-flex justify-content-between w-100" id="navbarSupportedContent">
            <div class="d-flex align-items-center">
              <!-- Search form -->
              <form class="navbar-search form-inline" id="navbar-search-main">
                <div class="input-group input-group-merge search-bar">
                    <span class="input-group-text" id="topbar-addon"><span class="fas fa-search"></span></span>
                    <input type="text" class="form-control" id="topbarInputIconLeft" placeholder="Search" aria-label="Search" aria-describedby="topbar-addon">
                </div>
              </form>
            </div>
            <!-- Navbar links -->
            <ul class="navbar-nav align-items-center">
              <li class="nav-item dropdown">
                <a class="nav-link text-dark me-lg-3 icon-notifications dropdown-toggle" data-unread-notifications="true" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <span class="icon icon-sm">
                    <span class="fas fa-bell bell-shake"></span>
                    <span class="icon-badge rounded-circle unread-notifications"></span>
                  </span>
                </a>
                <div class="dropdown-menu dashboard-dropdown dropdown-menu-lg dropdown-menu-center mt-2 py-0">
                  <div class="list-group list-group-flush">
                    <a href="#" class="text-center text-primary fw-bold border-bottom border-light py-3">Notifications</a>
                    <a href="#" class="list-group-item list-group-item-action border-bottom border-light">
                      <div class="row align-items-center">
                          <div class="col-auto">
                            <!-- Avatar -->
                            <img alt="Image placeholder" src="/static/assets/img/team/profile-picture-1.jpg" class="user-avatar lg-avatar rounded-circle">
                          </div>
                          <div class="col ps-0 ms-2">
                            <div class="d-flex justify-content-between align-items-center">
                                <div>
                                  <h4 class="h6 mb-0 text-small">Jose Leos</h4>
                                </div>
                                <div class="text-end">
                                  <small class="text-danger">a few moments ago</small>
                                </div>
                            </div>
                            <p class="font-small mt-1 mb-0">Added you to an event "Project stand-up" tomorrow at 12:30 AM.</p>
                          </div>
                      </div>
                    </a>
                    <a href="#" class="list-group-item list-group-item-action border-bottom border-light">
                      <div class="row align-items-center">
                          <div class="col-auto">
                            <!-- Avatar -->
                            <img alt="Image placeholder" src="/static/assets/img/team/profile-picture-2.jpg" class="user-avatar lg-avatar rounded-circle">
                          </div>
                          <div class="col ps-0 ms-2">
                            <div class="d-flex justify-content-between align-items-center">
                                <div>
                                  <h4 class="h6 mb-0 text-small">Neil Sims</h4>
                                </div>
                                <div class="text-end">
                                  <small class="text-danger">2 hrs ago</small>
                                </div>
                            </div>
                            <p class="font-small mt-1 mb-0">You've been assigned a task for "Awesome new project".</p>
                          </div>
                      </div>
                    </a>
                    <a href="#" class="list-group-item list-group-item-action border-bottom border-light">
                      <div class="row align-items-center">
                          <div class="col-auto">
                            <!-- Avatar -->
                            <img alt="Image placeholder" src="/static/assets/img/team/profile-picture-3.jpg" class="user-avatar lg-avatar rounded-circle">
                          </div>
                          <div class="col ps-0 m-2">
                            <div class="d-flex justify-content-between align-items-center">
                                <div>
                                  <h4 class="h6 mb-0 text-small">Roberta Casas</h4>
                                </div>
                                <div class="text-end">
                                  <small>5 hrs ago</small>
                                </div>
                            </div>
                            <p class="font-small mt-1 mb-0">Tagged you in a document called "First quarter financial plans",</p>
                          </div>
                      </div>
                    </a>
                    <a href="#" class="list-group-item list-group-item-action border-bottom border-light">
                      <div class="row align-items-center">
                          <div class="col-auto">
                            <!-- Avatar -->
                            <img alt="Image placeholder" src="/static/assets/img/team/profile-picture-4.jpg" class="user-avatar lg-avatar rounded-circle">
                          </div>
                          <div class="col ps-0 ms-2">
                            <div class="d-flex justify-content-between align-items-center">
                                <div>
                                  <h4 class="h6 mb-0 text-small">Joseph Garth</h4>
                                </div>
                                <div class="text-end">
                                  <small>1 d ago</small>
                                </div>
                            </div>
                            <p class="font-small mt-1 mb-0">New message: "Hey, what's up? All set for the presentation?"</p>
                          </div>
                      </div>
                    </a>
                    <a href="#" class="list-group-item list-group-item-action border-bottom border-light">
                      <div class="row align-items-center">
                          <div class="col-auto">
                            <!-- Avatar -->
                            <img alt="Image placeholder" src="/static/assets/img/team/profile-picture-5.jpg" class="user-avatar lg-avatar rounded-circle">
                          </div>
                          <div class="col ps-0 ms-2">
                            <div class="d-flex justify-content-between align-items-center">
                                <div>
                                  <h4 class="h6 mb-0 text-small">Bonnie Green</h4>
                                </div>
                                <div class="text-end">
                                  <small>2 hrs ago</small>
                                </div>
                            </div>
                            <p class="font-small mt-1 mb-0">New message: "We need to improve the UI/UX for the landing page."</p>
                          </div>
                      </div>
                    </a>
                    <a href="#" class="dropdown-item text-center text-primary fw-bold rounded-bottom py-3">View all</a>
                  </div>
                </div>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle pt-1 px-0" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  <div class="media d-flex align-items-center">
                    <div class="media-body ms-2 text-dark align-items-center d-none d-lg-block">
                      <span class="mb-0 font-small fw-bold">
                        Current User: <strong>{{ request.user.username }}</strong>
                      </span>
                    </div>
                  </div>
                </a>
                <div class="dropdown-menu dashboard-dropdown dropdown-menu-end mt-2 py-0">
                    <a class="dropdown-item rounded-top fw-bold" href="/mycrm/settings">
                      <span class="far fa-user-circle"></span>My Profile</a>
                    <a class="dropdown-item fw-bold" href="/mycrm/settings"><span class="fas fa-cog"></span>Settings</a>
                    <div role="separator" class="dropdown-divider my-0"></div>
                    <a class="dropdown-item rounded-bottom fw-bold" href="{% url 'mycrm:logout' %}">
                      <span class="fas fa-sign-out-alt text-danger"></span>Logout</a>
                </div>
              </li>
            </ul>
          </div>
        </div>
    </nav>
    

mycrm/templates/mycrm/includes/scripts.html
<!-- Core -->
<script src="/static/assets/vendor/@popperjs/core/dist/umd/popper.min.js"></script>
<script src="/static/assets/vendor/bootstrap/dist/js/bootstrap.min.js"></script>

<!-- Vendor JS -->
<script src="/static/assets/vendor/onscreen/dist/on-screen.umd.min.js"></script>

<!-- Slider -->
<script src="/static/assets/vendor/nouislider/distribute/nouislider.min.js"></script>

<!-- Smooth scroll -->
<script src="/static/assets/vendor/smooth-scroll/dist/smooth-scroll.polyfills.min.js"></script>

<!-- Charts -->
<script src="/static/assets/vendor/chartist/dist/chartist.min.js"></script>
<script src="/static/assets/vendor/chartist-plugin-tooltips/dist/chartist-plugin-tooltip.min.js"></script>

<!-- Datepicker -->
<script src="/static/assets/vendor/vanillajs-datepicker/dist/js/datepicker.min.js"></script>

<!-- Sweet Alerts 2 -->
<script src="/static/assets/vendor/sweetalert2/dist/sweetalert2.all.min.js"></script>

<!-- Moment JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.27.0/moment.min.js"></script>

<!-- Vanilla JS Datepicker -->
<script src="/static/assets/vendor/vanillajs-datepicker/dist/js/datepicker.min.js"></script>

<!-- Notyf -->
<script src="/static/assets/vendor/notyf/notyf.min.js"></script>

<!-- Simplebar -->
<script src="/static/assets/vendor/simplebar/dist/simplebar.min.js"></script>

<!-- Github buttons -->
<script async defer src="https://buttons.github.io/buttons.js"></script>

<!-- Volt JS -->
<script src="/static/assets/js/volt.js"></script>

<!-- JQUERY -->
<script src="https://code.jquery.com/jquery-3.5.0.js"></script>

mycrm/templates/mycrm/includes/settings-box.html
<div class="theme-settings card pt-2 collapse" id="theme-settings">
    <div class="card-body pt-4">
        <button type="button" class="btn-close theme-settings-close" aria-label="Close" data-bs-toggle="collapse"
            href="#theme-settings" role="button" aria-expanded="false" aria-controls="theme-settings"></button>
        <div class="d-flex justify-content-between align-items-center mb-3">
            <p class="m-0 mb-1 me-4 fs-7">Open source <span role="img" aria-label="gratitude">💛</span></p>
            <a class="github-button" href="https://github.com/app-generator/django-dashboard-volt"
                data-color-scheme="no-preference: dark; light: light; dark: light;" data-icon="octicon-star"
                data-size="large" data-show-count="true"
                aria-label="Star themesberg/volt-bootstrap-5-dashboard on GitHub">Star</a>
        </div>
        <a href="https://appseed.us/admin-dashboards/django-dashboard-volt" target="_blank"
            class="btn btn-primary mb-3 w-100">Download <i class="fas fa-download ms-2"></i></a>
        <p class="fs-7 text-gray-700 text-center">Available in the following technologies:</p>
        <div class="d-flex justify-content-center">
            <a class="me-3" href="https://themesberg.com/product/admin-dashboard/volt-bootstrap-5-dashboard"
                target="_blank">
                <img src="/static/assets/img/technologies/bootstrap-5-logo.svg" class="image image-xs">
            </a>
            <a href="https://demo.themesberg.com/volt-react-dashboard/#/" target="_blank">
                <img src="/static/assets/img/technologies/react-logo.svg" class="image image-xs">
            </a>
            <a href="https://appseed.us/admin-dashboards/flask-dashboard-volt" target="_blank">
                <img src="/static/assets/img/technologies/flask-logo.svg" class="image image-xs">
            </a>
            <a href="https://appseed.us/admin-dashboards/django-dashboard-volt" target="_blank">
                <img src="/static/assets/img/technologies/django-logo.svg" class="image image-xs">
            </a>                        
        </div>
    </div>
</div>

<div class="card theme-settings theme-settings-expand" id="theme-settings-expand">
    <div class="card-body p-3 py-2">
        <span class="fw-bold h6">
            <i class="fas fa-cogs me-1 fs-7"></i> Settings
        </span>
    </div>
</div>